name: Build and Upload to DigitalOcean Spaces

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Install Unity (example using GameCI)
    - name: Install Unity
      uses: game-ci/unity-installer@v3
      with:
        version: 2023.1.4f1  # Replace with your Unity version

    # Build the Unity project
    - name: Build Project
      run: |
        mkdir Build
        unity-editor -quit -batchmode -nographics -projectPath ./ -buildTarget WebGL -executeMethod BuildScript.BuildWebGL

    # Install AWS CLI
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    # Configure AWS CLI for DigitalOcean Spaces
    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.DO_SPACES_KEY }}
        aws configure set aws_secret_access_key ${{ secrets.DO_SPACES_SECRET }}
        aws configure set default.region ${{ secrets.DO_SPACES_REGION }}

    # Upload the Unity build folder to the DigitalOcean Space
    - name: Upload Build to DigitalOcean Space
      run: |
        aws s3 --endpoint-url=https://${{ secrets.DO_SPACES_REGION }}.digitaloceanspaces.com \
        cp ./Build/ s3://${{ secrets.DO_SPACES_BUCKET }}/UnityBuild/ --recursive
